package my.home.model.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table MSG_HISTORY_ITEM.
 */
public class MsgHistoryItem {

    private Long id;
    /**
     * Not-null value.
     */
    private String from;
    /**
     * Not-null value.
     */
    private String msg;

    public MsgHistoryItem() {
    }

    public MsgHistoryItem(Long id) {
        this.id = id;
    }

    public MsgHistoryItem(Long id, String from, String msg) {
        this.id = id;
        this.from = from;
        this.msg = msg;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Not-null value.
     */
    public String getFrom() {
        return from;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setFrom(String from) {
        this.from = from;
    }

    /**
     * Not-null value.
     */
    public String getMsg() {
        return msg;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setMsg(String msg) {
        this.msg = msg;
    }

}
