package my.home.model.datasource;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;
import my.home.model.entities.ChatItem;
import my.home.model.entities.HistoryItem;
import my.home.model.entities.MessageItem;
import my.home.model.entities.MsgHistoryItem;
import my.home.model.entities.Shortcut;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatItemDaoConfig;
    private final DaoConfig shortcutDaoConfig;
    private final DaoConfig historyItemDaoConfig;
    private final DaoConfig msgHistoryItemDaoConfig;
    private final DaoConfig messageItemDaoConfig;

    private final ChatItemDao chatItemDao;
    private final ShortcutDao shortcutDao;
    private final HistoryItemDao historyItemDao;
    private final MsgHistoryItemDao msgHistoryItemDao;
    private final MessageItemDao messageItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatItemDaoConfig = daoConfigMap.get(ChatItemDao.class).clone();
        chatItemDaoConfig.initIdentityScope(type);

        shortcutDaoConfig = daoConfigMap.get(ShortcutDao.class).clone();
        shortcutDaoConfig.initIdentityScope(type);

        historyItemDaoConfig = daoConfigMap.get(HistoryItemDao.class).clone();
        historyItemDaoConfig.initIdentityScope(type);

        msgHistoryItemDaoConfig = daoConfigMap.get(MsgHistoryItemDao.class).clone();
        msgHistoryItemDaoConfig.initIdentityScope(type);

        messageItemDaoConfig = daoConfigMap.get(MessageItemDao.class).clone();
        messageItemDaoConfig.initIdentityScope(type);

        chatItemDao = new ChatItemDao(chatItemDaoConfig, this);
        shortcutDao = new ShortcutDao(shortcutDaoConfig, this);
        historyItemDao = new HistoryItemDao(historyItemDaoConfig, this);
        msgHistoryItemDao = new MsgHistoryItemDao(msgHistoryItemDaoConfig, this);
        messageItemDao = new MessageItemDao(messageItemDaoConfig, this);

        registerDao(ChatItem.class, chatItemDao);
        registerDao(Shortcut.class, shortcutDao);
        registerDao(HistoryItem.class, historyItemDao);
        registerDao(MsgHistoryItem.class, msgHistoryItemDao);
        registerDao(MessageItem.class, messageItemDao);
    }

    public void clear() {
        chatItemDaoConfig.getIdentityScope().clear();
        shortcutDaoConfig.getIdentityScope().clear();
        historyItemDaoConfig.getIdentityScope().clear();
        msgHistoryItemDaoConfig.getIdentityScope().clear();
        messageItemDaoConfig.getIdentityScope().clear();
    }

    public ChatItemDao getChatItemDao() {
        return chatItemDao;
    }

    public ShortcutDao getShortcutDao() {
        return shortcutDao;
    }

    public HistoryItemDao getHistoryItemDao() {
        return historyItemDao;
    }

    public MsgHistoryItemDao getMsgHistoryItemDao() {
        return msgHistoryItemDao;
    }

    public MessageItemDao getMessageItemDao() {
        return messageItemDao;
    }
}
