package my.home.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table CHAT_ITEM.
 */
public class ChatItem {

    private Long id;
    /**
     * Not-null value.
     */
    private String content;
    private boolean isMe;
    private int state;
    private int seq;
    private java.util.Date date;

    public ChatItem() {
    }

    public ChatItem(Long id) {
        this.id = id;
    }

    public ChatItem(Long id, String content, boolean isMe, int state, int seq, java.util.Date date) {
        this.id = id;
        this.content = content;
        this.isMe = isMe;
        this.state = state;
        this.seq = seq;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Not-null value.
     */
    public String getContent() {
        return content;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setContent(String content) {
        this.content = content;
    }

    public boolean getIsMe() {
        return isMe;
    }

    public void setIsMe(boolean isMe) {
        this.isMe = isMe;
    }

    public int getState() {
        return state;
    }

    public void setState(int state) {
        this.state = state;
    }

    public int getSeq() {
        return seq;
    }

    public void setSeq(int seq) {
        this.seq = seq;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
